### ISSUE TITLE
Values for longitude/latitude

### ISSUE THREAD

**Issue by kaitlynmacinnis** [sfu-dhil/lim#8]
Hello,

When attempting to create entries for "Locations," I'm unable to put exact values for longitude and latitude, although I see these are correct for the previously created entry for "Edinburgh." For example, the longitude for Penrith should be -2.755508, but the database only seems to accept whole numbers. When I try to enter and save this, I get an error code stating: "Please enter a valid value. The two nearest valid values are -3 and -2."

Thank you,

Kaitlyn

**Comment by michael-joyce** [comment]
Fixed in 19ebae6705

**Comment by kaitlynmacinnis** [comment]
Thank you!
